version: '3'

services:
    app:
        container_name: app_${APP_NAME:?err}
        build:
            context: docker/php-fpm
        volumes:
            - ./:/var/www
            - ./docker/php-fpm/php.ini:/etc/php81/conf.d/php.ini
            - ./docker/php-fpm/docker.conf:/etc/php81//php-fpm.d/docker.conf
            - ./docker/php-fpm/zz-docker.conf:/etc/php81//php-fpm.d/zz-docker.conf
            - ./docker/php-fpm/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
            - ./docker/php-fpm/.ssh/id_rsa:/root/.ssh/id_rsa
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        depends_on:
            mysql:
                condition: service_healthy
    node:
        container_name: node_${APP_NAME:?err}
        build:
            context: docker/node
        volumes:
            - ./:/var/www
        ports:
            - "8081:8080"
            - "5173:5173"
        depends_on:
            - app
    nginx:
        container_name: nginx_${APP_NAME:?err}
        image: nginx:alpine
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "81:80"
        depends_on:
            - app
    mysql:
        container_name: mysql_${APP_NAME:?err}
        command: --default-authentication-plugin=mysql_native_password
        image: mysql
        environment:
            MYSQL_DATABASE: ${APP_NAME:?err}_db
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_USER: ${APP_NAME:?err}_user
            MYSQL_PASSWORD: pass
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3307:3306"
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 5s
            retries: 40
volumes:
    db_data:
        driver: local
