version: '3'

services:
  app:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal
  node:
    build:
      context: docker/node
    volumes:
      - ./:/var/www
    ports:
      - "8080:8080"
    networks:
      - internal
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - internal
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    environment:
      MYSQL_DATABASE: ${APP_NAME:?err}_db
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: ${APP_NAME:?err}_user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db_data:
    driver: local
